load("@kernel_toolchain_info//:dict.bzl", "CLANG_VERSION")
load("@rules_pkg//pkg:install.bzl", "pkg_install")
load("@rules_pkg//pkg:mappings.bzl", "pkg_files", "strip_prefix")
load("@rules_python//python:py_runtime_pair.bzl", "py_runtime_pair")
load("//build/kernel/kleaf:kernel.bzl", "kernel_build", "kernel_compile_commands")

kernel_build(
    name = "beagle_x15",
    outs = [
        "MLO",
        "u-boot.img",
    ],
    build_config = "build.config.beagle_x15",
    deps = [
        "//prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9:binaries",
    ],
)

pkg_files(
    name = "beagle_x15_dist_files",
    srcs = [":beagle_x15"],
    strip_prefix = strip_prefix.files_only(),
    visibility = ["//visibility:private"],
)

pkg_install(
    name = "beagle_x15_dist",
    srcs = [":beagle_x15_dist_files"],
    destdir = "out/u-boot/dist",
)

kernel_build(
    name = "crosvm_aarch64",
    outs = [
        "System.map",
        "u-boot",
        "u-boot.bin",
    ],
    build_config = "build.config.crosvm.aarch64",
    deps = [
        "//prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9:binaries",
    ],
)

kernel_compile_commands(
    name = "crosvm_aarch64_compile_commands",
    kernel_build = ":crosvm_aarch64",
)

pkg_files(
    name = "crosvm_aarch64_dist_files",
    srcs = [":crosvm_aarch64"],
    strip_prefix = strip_prefix.files_only(),
    visibility = ["//visibility:private"],
)

pkg_install(
    name = "crosvm_aarch64_dist",
    srcs = [":crosvm_aarch64_dist_files"],
    destdir = "out/u-boot/dist",
)

kernel_build(
    name = "kiwi",
    outs = [
        "System.map",
        "u-boot",
        "u-boot.rom",
    ],
    arch = "x86_64",
    build_config = "build.config.kiwi",
    deps = [
        "//prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9:binaries",
    ],
)

kernel_compile_commands(
    name = "kiwi_compile_commands",
    kernel_build = ":kiwi",
)

pkg_files(
    name = "kiwi_dist_files",
    srcs = [":kiwi"],
    strip_prefix = strip_prefix.files_only(),
    visibility = ["//visibility:private"],
)

pkg_install(
    name = "kiwi_dist",
    srcs = [":kiwi_dist_files"],
    destdir = "out/u-boot/dist",
)

kernel_build(
    name = "kiwi_p",
    outs = [
        "System.map",
        "u-boot",
        "u-boot.rom",
    ],
    arch = "x86_64",
    build_config = "build.config.kiwi_p",
    deps = [
        "//prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9:binaries",
    ],
)

kernel_compile_commands(
    name = "kiwi_p_compile_commands",
    kernel_build = ":kiwi_p",
)

pkg_files(
    name = "kiwi_p_dist_files",
    srcs = [":kiwi_p"],
    strip_prefix = strip_prefix.files_only(),
    visibility = ["//visibility:private"],
)

pkg_install(
    name = "kiwi_p_dist",
    srcs = [":kiwi_p_dist_files"],
    destdir = "out/u-boot/dist",
)

kernel_build(
    name = "qemu_x86_64",
    outs = [
        "System.map",
        "u-boot",
        "u-boot.rom",
    ],
    arch = "x86_64",
    build_config = "build.config.qemu.x86_64",
    deps = [
        "//prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9:binaries",
    ],
)

kernel_compile_commands(
    name = "qemu_x86_64_compile_commands",
    kernel_build = ":qemu_x86_64",
)

pkg_files(
    name = "qemu_x86_64_dist_files",
    srcs = [":qemu_x86_64"],
    strip_prefix = strip_prefix.files_only(),
    visibility = ["//visibility:private"],
)

pkg_install(
    name = "qemu_x86_64_dist",
    srcs = [":qemu_x86_64_dist_files"],
    destdir = "out/u-boot/dist",
)

kernel_build(
    name = "crosvm_x86",
    outs = [
        "System.map",
        "u-boot",
        "u-boot.rom",
    ],
    arch = "x86_64",
    build_config = "build.config.crosvm.x86",
    deps = [
        "//prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9:binaries",
    ],
)

kernel_compile_commands(
    name = "crosvm_x86_compile_commands",
    kernel_build = ":crosvm_x86",
)

pkg_files(
    name = "crosvm_x86_dist_files",
    srcs = [":crosvm_x86"],
    strip_prefix = strip_prefix.files_only(),
    visibility = ["//visibility:private"],
)

pkg_install(
    name = "crosvm_x86_dist",
    srcs = [":crosvm_x86_dist_files"],
    destdir = "out/u-boot/dist",
)

kernel_build(
    name = "crosvm_x86_64",
    outs = [
        "System.map",
        "u-boot",
        "u-boot.rom",
    ],
    arch = "x86_64",
    build_config = "build.config.crosvm.x86_64",
    deps = [
        "//prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9:binaries",
    ],
)

kernel_compile_commands(
    name = "crosvm_x86_64_compile_commands",
    kernel_build = ":crosvm_x86_64",
)

pkg_files(
    name = "crosvm_x86_64_dist_files",
    srcs = [":crosvm_x86_64"],
    strip_prefix = strip_prefix.files_only(),
    visibility = ["//visibility:private"],
)

pkg_install(
    name = "crosvm_x86_64_dist",
    srcs = [":crosvm_x86_64_dist_files"],
    destdir = "out/u-boot/dist",
)

kernel_build(
    name = "gem5_aarch64",
    outs = [
        "System.map",
        "u-boot",
        "u-boot.elf",
    ],
    build_config = "build.config.gem5.aarch64",
    deps = [
        "//prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9:binaries",
    ],
)

kernel_compile_commands(
    name = "gem5_aarch64_compile_commands",
    kernel_build = ":gem5_aarch64",
)

pkg_files(
    name = "gem5_aarch64_dist_files",
    srcs = [":gem5_aarch64"],
    strip_prefix = strip_prefix.files_only(),
    visibility = ["//visibility:private"],
)

pkg_install(
    name = "gem5_aarch64_dist",
    srcs = [":gem5_aarch64_dist_files"],
    destdir = "out/u-boot/dist",
)

kernel_build(
    name = "qemu_aarch64",
    outs = [
        "System.map",
        "u-boot",
        "u-boot.bin",
    ],
    build_config = "build.config.qemu.aarch64",
    deps = [
        "//prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9:binaries",
    ],
)

kernel_compile_commands(
    name = "qemu_aarch64_compile_commands",
    kernel_build = ":qemu_aarch64",
)

pkg_files(
    name = "qemu_aarch64_dist_files",
    srcs = [":qemu_aarch64"],
    strip_prefix = strip_prefix.files_only(),
    visibility = ["//visibility:private"],
)

pkg_install(
    name = "qemu_aarch64_dist",
    srcs = [":qemu_aarch64_dist_files"],
    destdir = "out/u-boot/dist",
)

kernel_build(
    name = "qemu_arm",
    outs = [
        "System.map",
        "u-boot",
        "u-boot.bin",
    ],
    arch = "arm",
    build_config = "build.config.qemu.arm",
    deps = [
        "//prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9:binaries",
    ],
)

kernel_compile_commands(
    name = "qemu_arm_compile_commands",
    kernel_build = ":qemu_arm",
)

pkg_files(
    name = "qemu_arm_dist_files",
    srcs = [":qemu_arm"],
    strip_prefix = strip_prefix.files_only(),
    visibility = ["//visibility:private"],
)

pkg_install(
    name = "qemu_arm_dist",
    srcs = [":qemu_arm_dist_files"],
    destdir = "out/u-boot/dist",
)

kernel_build(
    name = "qemu_riscv64",
    outs = [
        "System.map",
        "u-boot",
        "u-boot.bin",
    ],
    arch = "riscv64",
    build_config = "build.config.qemu.riscv64",
)

pkg_files(
    name = "qemu_riscv64_dist_files",
    srcs = [":qemu_riscv64"],
    strip_prefix = strip_prefix.files_only(),
    visibility = ["//visibility:private"],
)

pkg_install(
    name = "qemu_riscv64_dist",
    srcs = [":qemu_riscv64_dist_files"],
    destdir = "out/u-boot/dist",
)

kernel_build(
    name = "rockpi4",
    outs = [
        "idbloader.img",
        "u-boot.itb",
    ],
    build_config = "build.config.rockpi4",
    deps = [
        "//prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9:binaries",
    ],
)

pkg_files(
    name = "rockpi4_dist_files",
    srcs = [":rockpi4"],
    strip_prefix = strip_prefix.files_only(),
    visibility = ["//visibility:private"],
)

pkg_install(
    name = "rockpi4_dist",
    srcs = [":rockpi4_dist_files"],
    destdir = "out/u-boot-mainline/dist",
)

kernel_build(
    name = "xen_aarch64",
    outs = [
        "System.map",
        "u-boot",
        "u-boot.bin",
    ],
    build_config = "build.config.xen.aarch64",
    deps = [
        "//prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9:binaries",
    ],
)

pkg_files(
    name = "xen_aarch64_dist_files",
    srcs = [":xen_aarch64"],
    strip_prefix = strip_prefix.files_only(),
    visibility = ["//visibility:private"],
)

pkg_install(
    name = "xen_aarch64_dist",
    srcs = [":xen_aarch64_dist_files"],
    destdir = "out/u-boot/dist",
)

# Use SWIG enabled Python
py_runtime_pair(
    name = "py_runtime_pair",
    py3_runtime = "//prebuilts/clang/host/linux-x86/clang-{}:python3".format(
        CLANG_VERSION,
    ),
)

toolchain(
    name = "py_toolchain",
    toolchain = ":py_runtime_pair",
    toolchain_type = "@bazel_tools//tools/python:toolchain_type",
)
